steps:
  # Step 1: Install the Sonar Scanner CLI
  - name: "gcr.io/cloud-builders/wget"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-6.2.1.4610-linux-x64.zip
        unzip sonar-scanner-6.2.1.4610-linux-x64.zip
        mv sonar-scanner-6.2.1.4610-linux-x64 sonar-scanner

  # Step 2: Run the sonar scanner
  - name: "python:3.10"
    entrypoint: "bash"
    env:
      - SONAR_TOKEN=${SONAR_TOKEN}
    args:
      - "-c"
      - |
        sonar-scanner/bin/sonar-scanner \
          -Dsonar.projectKey=my-python-project \
          -Dsonar.sources=. \
          -Dsonar.host.url=http://<YOUR_VM_PUBLIC_IP>:9000 \
          -Dsonar.login=$SONAR_TOKEN

timeout: "900s"
